site_name: Infosec Getting Started
theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: slate
    accent: green
    primary: black
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.indexes

extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://infosec.exchange/@gradius
      name: gradius

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.superfences

plugins:
  - search
  - tags
  - offline

repo_url: https://github.com/gradiuscypher/infosec_getting_started/
repo_name: infosec_getting_started
