name: Upload to Bookstack
on: [push]
jobs:
  upload-to-bookstack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the files
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get changed files with JSON output
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          json: "true"
      - name: Show changed files JSON
        run: |
          echo "Added: ${{ steps.changed-files.outputs.added_files}}"
          echo "Modified: ${{ steps.changed-files.outputs.modified_files}}"
          echo "Deleted: ${{ steps.changed-files.outputs.deleted_files}}"
